server:
  port: ${PORT:5000}

base-url: /api

spring:
  application:
    name: taskManager

  profiles:
    active: dev

  liquibase:
    enabled: false
    change-log: classpath:db/changelog/changelog-master.xml

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop